### ISSUE TITLE
Yum in RHEL <=6.6 doesn't have --downloadonly 

### ISSUE THREAD

**Issue by Alibloke** [rackerlabs/auter#192]
When running Auter on a RHEL 6.6 device yum errored out:
WARNING: downloadonly option is not available

When I ran a yum install yum-plugin-downloadonly it upgraded yum instead as a later version of yum includes the downloadonly option.

My advice would be to require a specific version of yum, however I don't know exactly which version included the downloadonly option.  The best I can give you is the version of yum that didn't work:
yum-3.2.29-60.el6.noarch

**Comment by reaperzn** [comment]
@Alibloke That is exactly what the warning was added for. It should not be a hard failure unless you are specifically using the "ONLYINSTALLFROMPREP" option. We should probably build in a hard failure in this block:
https://github.com/rackerlabs/auter/blob/398ba8b4e8c823262805b1e32683ddab6e61cf37/auter.yumdnfModule#L87-L89

Something along the lines of:
```
if [[ "${ONLYINSTALLFROMPREP}" == "yes" ]]; then
  logit "ERROR: ONLYINSTALLFROMPREP set to 'yes' and --downloadonly option is not available"
else
  logit "WARNING: downloadonly option is not available"
fi
```

Auter does work with older versions of yum and the downloadonly option is not fundamental requirement for auter to work so adding a version dependency for yum seems a bit limiting. 

That said, assuming your case, auter will not download the updates due to the downloadonly option not being available, this will currently not be a failure. Following that, when `auter --apply`  is run, there will be no updates available and there will be no failure.  This is something we will need to look at adjusting.

**Comment by rhodesn** [comment]
Going to close this out since #200 was merged.
